package com.piston.mc.flyingmachinebackport.coremod;
// This file is automatically generated
// Do not edit this file directly
public interface CoremodInfo {
    String Id = "flyingmachinebackport";
    String Version = "1.0.0";
    String Group = "com.piston.mc.flyingmachinebackport";
    String GroupSlashed = "com/piston/mc/flyingmachinebackport";
    String CoremodGroup = "com.piston.mc.flyingmachinebackport.coremod";
    String CoremodGroupSlashed = "com/piston/mc/flyingmachinebackport/coremod";
}
