package pistonmc.flyingmachinebackport.coremod;

// This file is automatically generated
// Do not edit this file manually

public interface CoremodInfo {
    String Id = "flyingmachinebackport";
    String Version = "1.2.0";
    String Group = "pistonmc.flyingmachinebackport";
    String GroupInternal = "pistonmc/flyingmachinebackport";
    String CoremodGroup = "pistonmc.flyingmachinebackport.coremod";
    String CoremodGroupInternal = "pistonmc/flyingmachinebackport/coremod";
}

