package pistonmc.flyingmachinebackport;

// This file is automatically generated
// Do not edit this file manually

public interface ModInfo {
    String Id = "flyingmachinebackport";
    String Version = "1.2.0";
    String Group = "pistonmc.flyingmachinebackport";
    String GroupInternal = "pistonmc/flyingmachinebackport";
}

