package com.piston.mc.flyingmachinebackport;
// This file is automatically generated with mcmod.py
// Do not edit this file directly
public interface ModInfo {
    String Id = "flyingmachinebackport";
    String Version = "1.0";
}
    